In [1]:
import pandas as pd

#read dataset
df = pd.read_csv("flights.csv")
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2008,1,25,5,2204.0,1935,106.0,2257,XE,7676,...,4.0,17.0,0,NaN,0,0.0,0.0,0.0,0.0,129.0
99996,2008,1,26,6,1933.0,1935,2234.0,2257,XE,7676,...,4.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
99997,2008,1,27,7,2047.0,1935,2400.0,2257,XE,7676,...,6.0,18.0,0,NaN,0,23.0,0.0,0.0,0.0,40.0
99998,2008,1,28,1,1956.0,1935,2308.0,2257,XE,7676,...,5.0,25.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
99999,2008,1,29,2,1938.0,1935,2308.0,2257,XE,7676,...,5.0,41.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [2]:
df.isna().sum()

Year                     0
Month                    0
DayofMonth               0
DayOfWeek                0
DepTime               1142
CRSDepTime               0
ArrTime               1302
CRSArrTime               0
UniqueCarrier            0
FlightNum                0
TailNum               1142
ActualElapsedTime     1302
CRSElapsedTime           0
AirTime               1302
ArrDelay              1302
DepDelay              1142
Origin                   0
Dest                     0
Distance                 0
TaxiIn                1302
TaxiOut               1142
Cancelled                0
CancellationCode     98858
Diverted                 0
CarrierDelay         80371
WeatherDelay         80371
NASDelay             80371
SecurityDelay        80371
LateAircraftDelay    80371
dtype: int64

In [3]:
df = df.drop(['CancellationCode'],axis=1)

In [4]:
df.fillna(0,inplace=True)

In [5]:
df.isna().sum()

Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [6]:
newdf = df[df['FlightNum'] == 335]
newdf

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,810,4.0,8.0,0,0,0.0,0.0,0.0,0.0,0.0
164,2008,1,3,4,1052.0,1050,1603.0,1620,WN,335,...,1521,6.0,10.0,0,0,0.0,0.0,0.0,0.0,0.0
741,2008,1,3,4,1653.0,1650,1932.0,1930,WN,335,...,577,6.0,14.0,0,0,0.0,0.0,0.0,0.0,0.0
3437,2008,1,4,5,2002.0,1955,2208.0,2225,WN,335,...,810,4.0,14.0,0,0,0.0,0.0,0.0,0.0,0.0
3601,2008,1,4,5,1114.0,1050,1628.0,1620,WN,335,...,1521,13.0,6.0,0,0,0.0,0.0,0.0,0.0,0.0
4179,2008,1,4,5,1708.0,1650,1937.0,1930,WN,335,...,577,6.0,8.0,0,0,0.0,0.0,0.0,0.0,0.0
6672,2008,1,5,6,2000.0,1955,2214.0,2225,WN,335,...,810,4.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
6819,2008,1,5,6,1105.0,1050,1625.0,1620,WN,335,...,1521,3.0,16.0,0,0,0.0,0.0,0.0,0.0,0.0
7307,2008,1,5,6,1710.0,1650,1938.0,1930,WN,335,...,577,5.0,7.0,0,0,0.0,0.0,0.0,0.0,0.0
9607,2008,1,6,7,1959.0,1955,2211.0,2225,WN,335,...,810,13.0,11.0,0,0,0.0,0.0,0.0,0.0,0.0
9766,2008,1,6,7,1110.0,1050,1630.0,1620,WN,335,...,1521,6.0,17.0,0,0,0.0,0.0,0.0,0.0,0.0
10313,2008,1,6,7,1704.0,1650,1940.0,1930,WN,335,...,577,6.0,17.0,0,0,0.0,0.0,0.0,0.0,0.0
12912,2008,1,7,1,1951.0,1955,2159.0,2225,WN,335,...,810,5.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
13076,2008,1,7,1,1051.0,1050,1604.0,1620,WN,335,...,1521,3.0,16.0,0,0,0.0,0.0,0.0,0.0,0.0
13653,2008,1,7,1,1651.0,1650,1922.0,1930,WN,335,...,577,5.0,10.0,0,0,0.0,0.0,0.0,0.0,0.0
16348,2008,1,8,2,1955.0,1955,2201.0,2225,WN,335,...,810,4.0,8.0,0,0,0.0,0.0,0.0,0.0,0.0
16512,2008,1,8,2,1104.0,1050,1628.0,1620,WN,335,...,1521,8.0,15.0,0,0,0.0,0.0,0.0,0.0,0.0
17089,2008,1,8,2,1700.0,1650,1933.0,1930,WN,335,...,577,6.0,12.0,0,0,0.0,0.0,0.0,0.0,0.0
19784,2008,1,9,3,1951.0,1955,2202.0,2225,WN,335,...,810,5.0,14.0,0,0,0.0,0.0,0.0,0.0,0.0
19948,2008,1,9,3,0.0,1050,0.0,1620,WN,335,...,1521,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0
20525,2008,1,9,3,1651.0,1650,1924.0,1930,WN,335,...,577,6.0,11.0,0,0,0.0,0.0,0.0,0.0,0.0
23221,2008,1,10,4,1954.0,1955,2209.0,2225,WN,335,...,810,3.0,12.0,0,0,0.0,0.0,0.0,0.0,0.0
23385,2008,1,10,4,0.0,1050,0.0,1620,WN,335,...,1521,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0
23962,2008,1,10,4,1649.0,1650,1927.0,1930,WN,335,...,577,5.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
26658,2008,1,11,5,1950.0,1955,2201.0,2225,WN,335,...,810,4.0,10.0,0,0,0.0,0.0,0.0,0.0,0.0
26822,2008,1,11,5,1101.0,1050,1613.0,1620,WN,335,...,1521,5.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
27400,2008,1,11,5,1648.0,1650,1919.0,1930,WN,335,...,577,5.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
29886,2008,1,12,6,1955.0,1955,2211.0,2225,WN,335,...,810,4.0,9.0,0,0,0.0,0.0,0.0,0.0,0.0
30033,2008,1,12,6,1047.0,1050,1612.0,1620,WN,335,...,1521,4.0,16.0,0,0,0.0,0.0,0.0,0.0,0.0
30516,2008,1,12,6,1652.0,1650,1923.0,1930,WN,335,...,577,6.0,7.0,0,0,0.0,0.0,0.0,0.0,0.0
52955,2008,1,19,6,1703.0,1705,1756.0,1815,WN,335,...,258,3.0,8.0,0,0,0.0,0.0,0.0,0.0,0.0
75686,2008,1,26,6,1700.0,1705,1801.0,1815,WN,335,...,258,5.0,7.0,0,0,0.0,0.0,0.0,0.0,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Year               100000 non-null  int64
 1   Month              100000 non-null  int64
 2   DayofMonth         100000 non-null  int64
 3   DayOfWeek          100000 non-null  int64
 4   DepTime            100000 non-null  float64
 5   CRSDepTime         100000 non-null  int64
 6   ArrTime            100000 non-null  float64
 7   CRSArrTime         100000 non-null  int64
 8   UniqueCarrier      100000 non-null  object
 9   FlightNum          100000 non-null  int64
 10  TailNum            100000 non-null  object
 11  ActualElapsedTime  100000 non-null  float64
 12  CRSElapsedTime     100000 non-null  int64
 13  AirTime            100000 non-null  float64
 14  ArrDelay           100000 non-null  float64
 15  DepDelay           100000 non-null  float64
 16  Origin             100000 non-null  object
 17  Dest               100000 non-null  object
 18  Distance           100000 non-null  int64
 19  TaxiIn             100000 non-null  float64
 20  TaxiOut            100000 non-null  float64
 21  Cancelled          100000 non-null  int64
 22  Diverted           100000 non-null  int64
 23  CarrierDelay       100000 non-null  float64
 24  WeatherDelay       100000 non-null  float64
 25  NASDelay           100000 non-null  float64
 26  SecurityDelay      100000 non-null  float64
 27  LateAircraftDelay  100000 non-null  float64
dtypes: float64(13), int64(11), object(4)
memory usage: 21.4+ MB

In [8]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,810,4.0,8.0,0,0,0.0,0.0,0.0,0.0,0.0
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,810,5.0,10.0,0,0,0.0,0.0,0.0,0.0,0.0
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,515,3.0,17.0,0,0,0.0,0.0,0.0,0.0,0.0
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,515,3.0,7.0,0,0,0.0,0.0,0.0,0.0,0.0
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,515,3.0,10.0,0,0,2.0,0.0,0.0,0.0,32.0

In [9]:
df.to_csv('flights_updated.csv')